version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: payfan-laravel:1.0
    container_name: payfan-laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/html:cached
    networks:
      - payfan-network

  db:
    image: mysql:5.7
    container_name: payfan-mysql
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: payfan
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      # volumes:
      # - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - payfan-network

  nginx:
    image: nginx:stable-alpine
    container_name: payfan-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
      - ./html:/var/www/html:cached
    networks:
      - payfan-network

  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: payfan-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker/rabbitmq/data:/var/lib/rabbitmq
      - ./docker/rabbitmq/log:/var/log/rabbitmq
    networks:
      - payfan-network

networks:
  payfan-network:
    driver: bridge
